### PR TITLE
PiP view and Dependency updates 

### PR DESCRIPTION
**Pull request by RadGade**
added Picture in Picture view for the player and upgraded the electron and electron-builder versions

### CODE REVIEW

**Comment by carlelieser** [comment]
Hey, I really like where this is going, but unfortunately, at least to me, it doesn't look like the PiP view is working as intended. Also, the peers indicator is not something I'd like to go for. Flixerr is aimed towards being really minimalistic and user-friendly and I don't think lots of people want to see how many peers they're connected to as they're streaming.

**Comment by RadGade** [comment]
what do you mean by the PiP view is working as intended? are there any bugs in it

**Comment by RadGade** [comment]
also I don't think I have pushed the peers indicator change to this pull request, I built that for the version I am using as it helps me know how many peers are connected to swarm.

**Comment by carlelieser** [comment]
There aren't any bugs it's just I would expect the actual player to move/resize to the bottom right of the app so you can navigate and view different content.

**Comment by RadGade** [comment]
I don't how to style a PiP player and I couldn't any resources on that, but having the movie in smaller window in a corner as I did my work was a really great experience

**Comment by carlelieser** [comment]
Check out what got merged!

**Pull request closed without merging**
